// --- 1. HANDLE LOGOUT ---
function logout() {
    localStorage.clear();
    window.location = "login.php";
}

// --- 2. DYNAMIC FETCH FROM MODEL OUTPUT ---
// This fetches the JSON generated by your Python script
fetch("outputs/finaloccupancy.json")
    .then(response => {
        if (!response.ok) throw new Error("JSON not found");
        return response.json();
    })
    .then(data => {
        console.log("Data loaded:", data);

        // 🔹 A. Fill the Shortage Risk box
        const riskBox = document.getElementById("patientPrediction");
        if (riskBox && data.shortage_risk) {
            riskBox.innerHTML = `<strong>Shortage Risk:</strong> <span>${data.shortage_risk}</span>`;
        }

        // 🔹 B. Fill the Next Week's Table
        const occupancyBox = document.getElementById("occupancyResults");
        if (occupancyBox && data.forecast) {
            let tableHtml = `<strong>Next Week's Bed Occupancy:</strong>
                             <table style="width:100%; margin-top:10px; border-collapse: collapse;">
                                <tr style="border-bottom: 2px solid #eee;">
                                    <th style="text-align:left; padding: 5px;">Date</th>
                                    <th style="text-align:right; padding: 5px;">Occupancy</th>
                                </tr>`;

            data.forecast.forEach(row => {
                let roundedOcc = Math.round(row.Tuned_Predicted_Occupancy);
                tableHtml += `
                    <tr style="border-bottom: 1px solid #f9f9f9;">
                        <td style="padding:5px;">${row.Date}</td>
                        <td style="padding:5px; text-align:right; font-weight:bold;">${roundedOcc} Beds</td>
                    </tr>`;
            });

            tableHtml += `</table>`;
            occupancyBox.innerHTML = tableHtml;
        }

        // 🔹 C. Update "Example Prediction" placeholders if they exist
        // This ensures your "95%" dummy text is replaced by actual model math
        const latestPred = Math.round(data.forecast[0].Tuned_Predicted_Occupancy);
        if(document.getElementById("predOccupancy")) {
            document.getElementById("predOccupancy").innerText = latestPred + " Beds";
        }
    })
    .catch(err => {
        console.error("Error loading forecast data:", err);
        document.getElementById("forecastStatus").innerText = "Model Status: Error loading data";
    });
